In [6]:
import numpy as np

In [7]:
l = [i for i in range(20)]
np_arr = np.array(l)
np_arr, np_arr.dtype==np.int64, np_arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 True,
 (20,))

In [8]:
j = [4.5, -6.0, 'A', 'C', 0]
nph_arr = np.array(j, dtype='<U64')
nph_arr

array(['4.5', '-6.0', 'A', 'C', '0'], dtype='<U64')

In [9]:
array3 = np.array([[2.4,3],[4.91,7],[0,-1]])

array3.size, len(array3), array3.shape, array3.ndim, array3.dtype, array3.itemsize

(6, 3, (3, 2), 2, dtype('float64'), 8)

In [10]:
s = ['Aryan', 'Rohan', 'Rohtak Rai']
a = np.array(s)
a, a.dtype, a.itemsize


(array(['Aryan', 'Rohan', 'Rohtak Rai'], dtype='<U10'), dtype('<U10'), 40)

In [11]:
np.zeros((3,4)), np.ones((4,3))

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [12]:
np.arange(20, 27, 2), np.arange(10).reshape((2,5))


(array([20, 22, 24, 26]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [13]:
k = np.arange(20)
k.shape = (5,4) # inplace change
j = k.reshape((1,20)) # returns new 
print(k)
k.resize(1,20) # inplace change
k, j


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]))

In [14]:
arr1 = np.array([[ -7, 0, 10, 20],
				 [ -5, 1, 40, 200],
				 [ -1, 1, 4, 30]])
arr1[0:3, 1], arr1[0:3, 1:2], arr1[0:3, [1]], arr1[0:3, [1,3]], arr1[[0, 2], [0, 3]]

(array([0, 1, 1]),
 array([[0],
        [1],
        [1]]),
 array([[0],
        [1],
        [1]]),
 array([[  0,  20],
        [  1, 200],
        [  1,  30]]),
 array([-7, 30]))

In [15]:
a1 = np.array([[3,6],[4,2]])
a2 = np.array([[10,20],[15,12]])
a1+a2, a1-a2, a1*a2, a1@a2, a1**2

(array([[13, 26],
        [19, 14]]),
 array([[ -7, -14],
        [-11, -10]]),
 array([[ 30, 120],
        [ 60,  24]]),
 array([[120, 132],
        [ 70, 104]]),
 array([[ 9, 36],
        [16,  4]]))

In [16]:
a1.sum(0), a1, a2, np.sum(a1)

(array([7, 8]),
 array([[3, 6],
        [4, 2]]),
 array([[10, 20],
        [15, 12]]),
 15)

In [17]:

np.add(a1, a2), a1,a2 #no inplace

(array([[13, 26],
        [19, 14]]),
 array([[3, 6],
        [4, 2]]),
 array([[10, 20],
        [15, 12]]))

In [18]:
np.concatenate((a1, a2), axis=1),

print(np.hstack((a1, a2)))
print(np.vstack((a1, a2)))

comb = np.hstack((a1, a2))

print(comb)
a1, a2

[[ 3  6 10 20]
 [ 4  2 15 12]]
[[ 3  6]
 [ 4  2]
 [10 20]
 [15 12]]
[[ 3  6 10 20]
 [ 4  2 15 12]]


(array([[3, 6],
        [4, 2]]),
 array([[10, 20],
        [15, 12]]))

In [19]:
print(comb)
np.hsplit(comb, [1,3]), np.split(comb, [1,3], axis = 1)

[[ 3  6 10 20]
 [ 4  2 15 12]]


([array([[3],
         [4]]),
  array([[ 6, 10],
         [ 2, 15]]),
  array([[20],
         [12]])],
 [array([[3],
         [4]]),
  array([[ 6, 10],
         [ 2, 15]]),
  array([[20],
         [12]])])

In [20]:
np.max(a1), np.max(comb), np.max(a1, axis = 1), a1.max(axis=0), np.std(a1), np.mean(a1)

(6, 20, array([6, 4]), array([4, 6]), 1.479019945774904, 3.75)

In [21]:
fnp = np.loadtxt('students.csv',skiprows=1,usecols=(1,2,3), delimiter=',', dtype=int, unpack=False)
fnp
#use unpack to transpose

array([[78, 67, 56],
       [76, 75, 47],
       [84, 59, 60],
       [67, 72, 54]])

In [22]:
ffnp = np.genfromtxt('marks.csv', usecols=(1,2,3), skip_header=1, delimiter=',', dtype=int, missing_values=[''],filling_values=989) # missing values tells which string is treated as missing value
ffnp

array([[ 36,  18,  57],
       [989,  23,  45],
       [ 43,  51, 989],
       [ 41,  40,  60],
       [ 13,  18,  27]])

In [25]:
arr = np.array([1,2,3,4,5,6])

In [27]:
arr[[True, True, False, True, False, True]]

array([1, 2, 4, 6])